org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
maven_group=me.wolfii
archives_base_name=allthelogs
mod_version=0.1.0

# Dependencies
fabric_api_version=0.158.0+26.2
owo_version=0.13.1+26.2
modmenu_version=20.0.1
