[versions]
duckdb = "1.5.5.1"
commons-compress = "1.28.0"
xz = "1.12"
junit = "5.14.0"
juniversalchardet = "2.5.0"

[libraries]
duckdb-jdbc = { module = "org.duckdb:duckdb_jdbc", version.ref = "duckdb" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
xz = { module = "org.tukaani:xz", version.ref = "xz" }
juniversalchardet = { module = "com.github.albfernandez:juniversalchardet", version.ref = "juniversalchardet" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.14.0" }
